name: Build and push Docker image

on:
  push:
    branches:
      - trunk

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get commit tag
      id: get_tag
      run: echo "::set-output name=tag::$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))"
      shell: bash

    - name: Build Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/cringe_radio:${{ steps.get_tag.outputs.tag || github.sha }}

    - name: Push Docker image
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cringe_radio:${{ steps.get_tag.outputs.tag || github.sha }}
  deploy:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            /home/githubci/upgrade-cringeradio ${{ github.sha }}